### ISSUE TITLE
Any plans for other component distributions?

### ISSUE THREAD

**Issue by sdwfrost** [jwmi/BayesianMixtures.jl#3]
Hi @jwmi !

Do you have plans to extend this to include other component distributions (e.g. Bernoulli)?

**Comment by jwmi** [comment]
Hi Simon!
I don't have any plans to add more component distributions in the immediate future, but feel free to implement a model and do a pull request if you are interested.  I wrote the package so that it is easy to add more models without any modifications to the algorithms themselves.

Cheers,
Jeff

On Thu, Oct 4, 2018 at 11:39 AM Simon Frost <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi @jwmi<https://github.com/jwmi> !

Do you have plans to extend this to include other component distributions (e.g. Bernoulli)?
